# profiles.yml - DuckDB connection configuration for dbt

ecommerce_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'ecommerce.duckdb'
      schema: main
      threads: 4

    prod:
      type: duckdb
      path: 'ecommerce_prod.duckdb'
      schema: main
      threads: 8
