# dbt_project.yml - E-Commerce Analytics Project Configuration

name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

# Project profile (connects to DuckDB)
profile: 'ecommerce_analytics'

# Directories
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Model configurations
models:
  ecommerce_analytics:
    # Staging models - clean and standardize raw data
    staging:
      +materialized: view
      +schema: staging
      +docs:
        node_color: "#F7931E"  # Orange

    # Intermediate models - business logic transformations
    intermediate:
      +materialized: view
      +schema: intermediate
      +docs:
        node_color: "#7CB9E8"  # Blue

    # Mart models - final analytics-ready tables
    marts:
      +materialized: view # DBT recommends using 'view' by default unless query time is long, then use 'table'
      +schema: marts
      +docs:
        node_color: "#50C878"  # Green

# Seed configurations
seeds:
  ecommerce_analytics:
    +schema: seeds

# Snapshot configurations
snapshots:
  ecommerce_analytics:
    +target_schema: snapshots

# Testing
data_tests:
  ecommerce_analytics:
    +store_failures: true
    +schema: test_results

# Documentation
vars:
  # Project variables
  start_date: '2016-09-01'
  end_date: '2018-08-31'

  # Business rules
  rfm_recency_days: 365
  late_delivery_threshold_days: 0
  high_value_customer_threshold: 1000  # R$ Brazilian Real
